### ISSUE TITLE
Todo: 

### ISSUE THREAD

**Issue by amarjandu** [sophietait/microblog#1]
## TODO
* [x] create class object that accepts file as argument, form constructor that parses file for filling in variables that hold data.

* [x] Create methods for getting cool stuff from within object (highest elevation, total distance etc)

* [ ] Create ways to load the object into a json format for web.

* [ ] Upload objects into database, create constructor that gets information from database

* [ ] Be able request particular “run” from the database, needs unique ID

* [ ] Be able to get all the runs from the database, attached to a user

* [ ] Provide ways to download the information back from the browser

* [ ] Provide a user interface to view all the data

* [ ] Create ways for someone to put their run into the database, server needs to parse the file for validity
